



 //1
 //0
 //13
 //22
 // 
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// Les informations générales relatives à un assembly dépendent de 
// l'ensemble d'attributs suivant. Changez les valeurs de ces attributs pour modifier les informations
// associées à un assembly.
[assembly: AssemblyTitle("BLS.Infrastructure")]
[assembly: AssemblyDescription("This a common tools library")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("BusinessLine")]
[assembly: AssemblyProduct("BLS.Infrastructure")]
[assembly: AssemblyCopyright("Copyright ©  2015")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// L'affectation de la valeur false à ComVisible rend les types invisibles dans cet assembly 
// aux composants COM.  Si vous devez accéder à un type dans cet assembly à partir de 
// COM, affectez la valeur true à l'attribut ComVisible sur ce type.
[assembly: ComVisible(false)]

// Le GUID suivant est pour l'ID de la typelib si ce projet est exposé à COM
[assembly: Guid("d9878e87-2c6e-4dec-948a-5a6a60681809")]
  
[assembly: AssemblyFileVersion("1.0.13.22")]
[assembly: AssemblyVersion("1.0.13.22")]
[assembly: AssemblyInformationalVersion("1.0.13.22")]